import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const sb=createClient('https://rmvfrgpampxduldzfwxi.supabase.co','sb_publishable_Y94dITMxDgGpH6ZnINbWjw_5w5KMW_c');
const $=id=>document.getElementById(id),token=new URLSearchParams(location.search).get('token');
const T={en:{title:'Additional overnight guest',intro:'Please register before staying overnight.',name:'Full name',city:'City / place of residence',country:'Country',countryPlaceholder:'Select a country',arr:'Arrival',dep:'Departure',decl:'I confirm that the information is complete and correct.',submit:'Submit guest registration',done:'Thank you. Your guest registration has been submitted.',successTitle:'Registration complete',website:'Visit Nijmegen Guest Rooms',bad:'This registration link is invalid, expired or already used.',fee:n=>`Additional guest fee: €${Number(n).toFixed(2)} per night, including tourist tax.`},nl:{title:'Overnachtende gast',intro:'Registreer je gegevens voordat je blijft overnachten.',name:'Volledige naam',city:'Woonplaats',country:'Land',countryPlaceholder:'Kies een land',arr:'Aankomst',dep:'Vertrek',decl:'Ik bevestig dat de ingevulde gegevens volledig en juist zijn.',submit:'Gastenregistratie versturen',done:'Bedankt. Je gastenregistratie is verstuurd.',successTitle:'Registratie voltooid',website:'Naar Nijmegen Guest Rooms',bad:'Deze registratielink is ongeldig, verlopen of al gebruikt.',fee:n=>`Toeslag extra gast: €${Number(n).toFixed(2)} per nacht, inclusief toeristenbelasting.`}};
let lang=(navigator.language||'en').toLowerCase().startsWith('nl')?'nl':'en',invite=null;
const COUNTRIES=['Afghanistan','Albania','Algeria','Argentina','Australia','Austria','Belgium','Brazil','Bulgaria','Canada','Chile','China','Colombia','Croatia','Curaçao','Cyprus','Czechia','Denmark','Egypt','Estonia','Finland','France','Germany','Ghana','Greece','Hungary','Iceland','India','Indonesia','Iran','Ireland','Israel','Italy','Japan','Kenya','Latvia','Lithuania','Luxembourg','Malaysia','Malta','Mexico','Morocco','Netherlands','New Zealand','Nigeria','North Macedonia','Norway','Pakistan','Peru','Philippines','Poland','Portugal','Romania','Serbia','Singapore','Slovakia','Slovenia','South Africa','South Korea','Spain','Sweden','Switzerland','Taiwan','Thailand','Turkey','Ukraine','United Arab Emirates','United Kingdom','United States','Vietnam','Zimbabwe'];
function populateCountries(){const el=$('country'),v=el.value;el.innerHTML=`<option value="">${T[lang].countryPlaceholder}</option>`+COUNTRIES.map(c=>`<option value="${c}">${c}</option>`).join('');el.value=v;}
function text(){let x=T[lang];document.documentElement.lang=lang;$('title').textContent=x.title;$('intro').textContent=x.intro;$('nameL').textContent=x.name;$('cityL').textContent=x.city;$('countryL').textContent=x.country;$('inL').textContent=x.arr;$('outL').textContent=x.dep;$('declT').textContent=x.decl;$('submit').textContent=x.submit;populateCountries();$('successTitle').textContent=x.successTitle;$('successText').textContent=x.done;$('websiteBtn').textContent=x.website;if(invite)$('fee').textContent=x.fee(invite.fee_per_night)}
$('en').onclick=()=>{lang='en';text()};$('nl').onclick=()=>{lang='nl';text()};
async function load(){if(!token){$('msg').textContent=T[lang].bad;return}let {data,error}=await sb.rpc('get_additional_guest_invite',{p_token:token});let r=Array.isArray(data)?data[0]:data;if(error||!r||!r.valid||r.already_submitted){$('msg').textContent=T[lang].bad;return}invite=r;$('in').value=r.checkin_date;$('out').value=r.checkout_date;$('form').classList.remove('hidden');text()}
$('submit').onclick=async()=>{let x=T[lang];if(!$('name').value.trim()||!$('city').value.trim()||!$('country').value.trim()||!$('decl').checked){$('msg').textContent=lang==='nl'?'Vul alle verplichte velden in.':'Complete all required fields.';return}const ci=$('in').value,co=$('out').value;if(!ci||!co||co<=ci||ci<invite.checkin_date||co>invite.checkout_date){$('msg').textContent=lang==='nl'?'Kies geldige verblijfsdata binnen de boekingsperiode.':'Choose valid stay dates within the booking period.';return}let {error}=await sb.rpc('submit_additional_guest_registration',{p_token:token,p_full_name:$('name').value.trim(),p_city:$('city').value.trim(),p_country:$('country').value.trim(),p_checkin_date:ci,p_checkout_date:co,p_declaration_accepted:true});if(error){$('msg').textContent=error.message;return}$('form').classList.add('hidden');$('msg').textContent='';$('success').classList.remove('hidden')};text();load();